export { default as  LandingPage } from './LandingPage'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as Profile } from './Profile'
export {default as MapCont} from './MapCont'
export {default as EditProfile} from './EditProfile'
